sudo: required
services:
    - docker

before_install:
    - docker build -t andrecouture/docker-react -f Dockerfile.dev .  

script:
    - docker run -e CI=true andrecouture/docker-react npm run test -- --coverage
    